<?php
/**
 * Custom Landing Page Fields
 */

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_hero',
		'title' => 'Hero',
		'fields' => array (
			array (
				'key' => 'field_56c97e090df6e',
				'label' => 'Hero Image',
				'name' => 'hero_image',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_56c97e230df6f',
				'label' => 'Hero Title',
				'name' => 'hero_title',
				'type' => 'text',
				'instructions' => 'Use <br/> for line breaks on the title.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56c97e650df70',
				'label' => 'Hero Paragraph',
				'name' => 'hero_paragraph',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_56c98851c610a',
				'label' => 'Hero Logo',
				'name' => 'hero_logo',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'landing-page.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'the_content',
				1 => 'excerpt',
				2 => 'custom_fields',
				3 => 'discussion',
				4 => 'comments',
				5 => 'revisions',
				6 => 'slug',
				7 => 'author',
				8 => 'format',
				9 => 'featured_image',
				10 => 'categories',
				11 => 'tags',
				12 => 'send-trackbacks',
			),
		),
		'menu_order' => 1,
	));
	register_field_group(array (
		'id' => 'acf_about-us',
		'title' => 'About Us',
		'fields' => array (
			array (
				'key' => 'field_56c97ed96cc9f',
				'label' => 'About Us Title',
				'name' => 'about_us_title',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56c97f3243956',
				'label' => 'About Us Paragraph',
				'name' => 'about_us_paragraph',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'landing-page.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'the_content',
				1 => 'excerpt',
				2 => 'custom_fields',
				3 => 'discussion',
				4 => 'comments',
				5 => 'revisions',
				6 => 'slug',
				7 => 'author',
				8 => 'format',
				9 => 'featured_image',
				10 => 'categories',
				11 => 'tags',
				12 => 'send-trackbacks',
			),
		),
		'menu_order' => 2,
	));
	register_field_group(array (
		'id' => 'acf_services',
		'title' => 'Services',
		'fields' => array (
			array (
				'key' => 'field_56c97f8673057',
				'label' => 'Services Title',
				'name' => 'services_title',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56c97fa073058',
				'label' => 'Services Paragraph',
				'name' => 'services_paragraph',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'landing-page.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'the_content',
				1 => 'excerpt',
				2 => 'custom_fields',
				3 => 'discussion',
				4 => 'comments',
				5 => 'revisions',
				6 => 'slug',
				7 => 'author',
				8 => 'format',
				9 => 'featured_image',
				10 => 'categories',
				11 => 'tags',
				12 => 'send-trackbacks',
			),
		),
		'menu_order' => 3,
	));
	register_field_group(array (
		'id' => 'acf_what-we-do',
		'title' => 'What We Do',
		'fields' => array (
			array (
				'key' => 'field_56c97faf221e4',
				'label' => 'What We Do Title',
				'name' => 'what_we_do_title',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56c98b01c75d3',
				'label' => 'What We Do Logo 1',
				'name' => 'what_we_do_logo_1',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_56c98ae8c75d2',
				'label' => 'What We Do Subtitle 1',
				'name' => 'what_we_do_subtitle_1',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56c97fc8221e5',
				'label' => 'What We Do Paragraph 1',
				'name' => 'what_we_do_paragraph_1',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_56c98b75b43f9',
				'label' => 'What We Do Logo 2',
				'name' => 'what_we_do_logo_2',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_56c98b4b53612',
				'label' => 'What We Do Subtitle 2',
				'name' => 'what_we_do_subtitle_2',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56c98b1f85798',
				'label' => 'What We Do Paragraph 2',
				'name' => 'what_we_do_paragraph_2',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_56c98b75b43f8',
				'label' => 'What We Do Logo 3',
				'name' => 'what_we_do_logo_3',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_56c98b4a53611',
				'label' => 'What We Do Subtitle 3',
				'name' => 'what_we_do_subtitle_3',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56c98b1e85797',
				'label' => 'What We Do Paragraph 3',
				'name' => 'what_we_do_paragraph_3',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'landing-page.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'the_content',
				1 => 'excerpt',
				2 => 'custom_fields',
				3 => 'discussion',
				4 => 'comments',
				5 => 'revisions',
				6 => 'slug',
				7 => 'author',
				8 => 'format',
				9 => 'featured_image',
				10 => 'categories',
				11 => 'tags',
				12 => 'send-trackbacks',
			),
		),
		'menu_order' => 4,
	));
	register_field_group(array (
		'id' => 'acf_gallery',
		'title' => 'Gallery',
		'fields' => array (
			array (
				'key' => 'field_56c97ff72c528',
				'label' => 'Gallery Title 1',
				'name' => 'gallery_title_1',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56c982062c529',
				'label' => 'Gallery Paragraph 1',
				'name' => 'gallery_paragraph_1',
				'type' => 'textarea',
				'default_value' => '250 character limit',
				'placeholder' => '',
				'maxlength' => 250,
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_56c9823e2c52a',
				'label' => 'Gallery Image 1',
				'name' => 'gallery_image_1',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_56c983017d56c',
				'label' => 'Gallery Title 2',
				'name' => 'gallery_title_2',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56c984709f8d9',
				'label' => 'Gallery Paragraph 2',
				'name' => 'gallery_paragraph_2',
				'type' => 'textarea',
				'default_value' => '250 character limit',
				'placeholder' => '',
				'maxlength' => 250,
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_56c983bfa7cc7',
				'label' => 'Gallery Image 2',
				'name' => 'gallery_image_2',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_56c983017d56b',
				'label' => 'Gallery Title 3',
				'name' => 'gallery_title_3',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56c984709f8d8',
				'label' => 'Gallery Paragraph 3',
				'name' => 'gallery_paragraph_3',
				'type' => 'textarea',
				'default_value' => '250 character limit',
				'placeholder' => '',
				'maxlength' => 250,
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_56c983bea7cc6',
				'label' => 'Gallery Image 3',
				'name' => 'gallery_image_3',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_56c983007d56a',
				'label' => 'Gallery Title 4',
				'name' => 'gallery_title_4',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56c9846f9f8d7',
				'label' => 'Gallery Paragraph 4',
				'name' => 'gallery_paragraph_4',
				'type' => 'textarea',
				'default_value' => '250 character limit',
				'placeholder' => '',
				'maxlength' => 250,
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_56c983bea7cc5',
				'label' => 'Gallery Image 4',
				'name' => 'gallery_image_4',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_56c982ff7d569',
				'label' => 'Gallery Title 5',
				'name' => 'gallery_title_5',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56c9846f9f8d6',
				'label' => 'Gallery Paragraph 5',
				'name' => 'gallery_paragraph_5',
				'type' => 'textarea',
				'default_value' => '250 character limit',
				'placeholder' => '',
				'maxlength' => 250,
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_56c983bda7cc4',
				'label' => 'Gallery Image 5',
				'name' => 'gallery_image_5',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_56c982fe7d568',
				'label' => 'Gallery Title 6',
				'name' => 'gallery_title_6',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56c9846e9f8d5',
				'label' => 'Gallery Paragraph 6',
				'name' => 'gallery_paragraph_6',
				'type' => 'textarea',
				'default_value' => '250 character limit',
				'placeholder' => '',
				'maxlength' => 250,
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_56c983bca7cc3',
				'label' => 'Gallery Image 6',
				'name' => 'gallery_image_6',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'landing-page.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'the_content',
				1 => 'excerpt',
				2 => 'custom_fields',
				3 => 'discussion',
				4 => 'comments',
				5 => 'revisions',
				6 => 'slug',
				7 => 'author',
				8 => 'format',
				9 => 'featured_image',
				10 => 'categories',
				11 => 'tags',
				12 => 'send-trackbacks',
			),
		),
		'menu_order' => 5,
	));
	register_field_group(array (
		'id' => 'acf_contact-us',
		'title' => 'Contact Us',
		'fields' => array (
			array (
				'key' => 'field_56c9a385adbda',
				'label' => 'Contact Us Title',
				'name' => 'contact_us_title',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56c98083ed781',
				'label' => 'Contact Us Paragraph',
				'name' => 'contact_us_paragraph',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_56c98092ed782',
				'label' => 'Contact Us Button Text',
				'name' => 'contact_us_button_text',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56c9a4aa86038',
				'label' => 'Contact Us Popup Title',
				'name' => 'contact_us_popup_title',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56c980a7ed783',
				'label' => 'Contact Us Popup Field',
				'name' => 'contact_us_popup_field',
				'type' => 'textarea',
				'instructions' => 'Paste Contact Form HTML in here.',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'html',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'landing-page.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'the_content',
				1 => 'excerpt',
				2 => 'custom_fields',
				3 => 'discussion',
				4 => 'comments',
				5 => 'revisions',
				6 => 'slug',
				7 => 'author',
				8 => 'format',
				9 => 'featured_image',
				10 => 'categories',
				11 => 'tags',
				12 => 'send-trackbacks',
			),
		),
		'menu_order' => 6,
	));
	register_field_group(array (
		'id' => 'acf_footer',
		'title' => 'Footer',
		'fields' => array (
			array (
				'key' => 'field_56c9802708f7a',
				'label' => 'Footer Logo',
				'name' => 'footer_logo',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_56c9803808f7b',
				'label' => 'Footer Text',
				'name' => 'footer_text',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'landing-page.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'the_content',
				1 => 'excerpt',
				2 => 'custom_fields',
				3 => 'discussion',
				4 => 'comments',
				5 => 'revisions',
				6 => 'slug',
				7 => 'author',
				8 => 'format',
				9 => 'featured_image',
				10 => 'categories',
				11 => 'tags',
				12 => 'send-trackbacks',
			),
		),
		'menu_order' => 7,
	));
}
